public enum TokenType
{
    ORIGIN, SCALE, ROT, IS, COLOR,
    TO, STEP, DRAW, FOR, FROM,
    T, ID,
    SEMICO, L_BRACKET, R_BRACKET, COMMA,
    PLUS, MINUS, MUL, DIV, POWER,
    FUNC,
    CONST_ID,
    NONTOKEN,
    ERRTOKEN,
    COMMENT,
    NEXT_LINE,
}
